name: Prettier on Push

on:
  push:
    branches:
      - master # 또는 main 브랜치일 경우 'main'으로

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add . ':!**/.github/workflows/**'
          git commit -m "Format code with Prettier" || echo "No changes to commit"
          git push